import pygame

WIDTH = 1280
HEIGHT = 720
WINSIZE = (WIDTH, HEIGHT)

# ALIGNMENT = 2
ALIGNMENT_FACTOR = 1.0
ALIGNMENT_PERCEPTION = 50

# COHESION = 2
COHESION_FACTOR = 1.0
COHESION_PERCEPTION = 100

# SEPARATION = 2
SEPARATION_FACTOR = 1.5
SEPARATION_PERCEPTION = 50

BLACK = pygame.Color(0, 0, 0)         # Black
WHITE = pygame.Color(255, 255, 255)   # White