import pygame

WIDTH = 1280
HEIGHT = 720
WINSIZE = (WIDTH, HEIGHT)

# if WIDTH < 640 or HEIGHT < 480:

global ALIGNMENT_FACTOR, COHESION_FACTOR, SEPARATION_FACTOR
ALIGNMENT_FACTOR = 1.0
ALIGNMENT_PERCEPTION = 50

COHESION_FACTOR = 1.0
COHESION_PERCEPTION = 100

SEPARATION_FACTOR = 1.5
SEPARATION_PERCEPTION = 50

SLIDER_WIDTH = WIDTH // 4
SLIDER_HEIGHT = 30
LABEL_HEIGHT = 20
SLIDER_SPACING = 20

TOTAL_UI_WIDTH = 3 * SLIDER_WIDTH + 2 * SLIDER_SPACING
START_X = (WIDTH - TOTAL_UI_WIDTH) // 2
START_Y = HEIGHT - SLIDER_HEIGHT - 20
LABEL_Y = START_Y - LABEL_HEIGHT - 5

BLACK = pygame.Color(0, 0, 0)         # Black
WHITE = pygame.Color(255, 255, 255)   # White